package org.notamusic.app.ui.editor

import android.content.Context
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Path
import android.view.MotionEvent
import android.view.ScaleGestureDetector
import android.view.View
import org.notamusic.app.domain.model.Accidental
import org.notamusic.app.domain.notation.*
import kotlin.math.abs
import kotlin.math.max

class ScoreEditorView(context: Context) : View(context) {
    private val p=Paint(Paint.ANTI_ALIAS_FLAG); private val engine get()=ScoreSession.engine
    private val store=org.notamusic.app.data.persistence.ScoreFileStore(context)
    private val groups=linkedMapOf("Notes" to listOf(EditorTool.WHOLE,EditorTool.HALF,EditorTool.QUARTER,EditorTool.EIGHTH,EditorTool.SIXTEENTH,EditorTool.THIRTY_SECOND),"Silences" to listOf(EditorTool.REST_WHOLE,EditorTool.REST_HALF,EditorTool.REST_QUARTER,EditorTool.REST_EIGHTH,EditorTool.REST_SIXTEENTH,EditorTool.REST_THIRTY_SECOND),"Ajouts" to listOf(EditorTool.SELECT,EditorTool.ERASER,EditorTool.DOT,EditorTool.DOUBLE_DOT,EditorTool.TIE,EditorTool.SLUR,EditorTool.TUPLET),"Ornements" to listOf(EditorTool.TRILL,EditorTool.MORDENT,EditorTool.INVERTED_MORDENT,EditorTool.TURN,EditorTool.INVERTED_TURN,EditorTool.STACCATO,EditorTool.SHORT_STACCATO,EditorTool.ACCENT,EditorTool.FERMATA,EditorTool.TREMOLO,EditorTool.GRACE),"Dynamiques" to listOf(EditorTool.PPP,EditorTool.PP,EditorTool.P,EditorTool.MP,EditorTool.MF,EditorTool.F,EditorTool.FF,EditorTool.FFF,EditorTool.CRESCENDO,EditorTool.DIMINUENDO))
    private var group="Notes"; private var tool=EditorTool.QUARTER; private var scrollX=0f; private var scrollY=0f; private var scale=1f; private var dx=0f; private var dy=0f; private var moving=false
    private val zoom=ScaleGestureDetector(context,object:ScaleGestureDetector.SimpleOnScaleGestureListener(){override fun onScale(d:ScaleGestureDetector):Boolean{scale=(scale*d.scaleFactor).coerceIn(.6f,2.5f);invalidate();return true}})
    override fun onDraw(c:Canvas){c.drawColor(0xfffaf9f6.toInt()); toolbar(c);c.save();c.scale(scale,scale);c.translate(-scrollX,92f-scrollY);score(c);c.restore()}
    private fun toolbar(c:Canvas){p.style=Paint.Style.FILL;p.color=0xffe6e2dc.toInt();c.drawRect(0f,0f,width.toFloat(),90f,p);var x=4f;p.textSize=11f;groups.keys.forEach{n->p.color=if(n==group)0xffb9cbe8.toInt()else 0xffd3d0ca.toInt();c.drawRect(x,4f,x+82,28f,p);p.color=0xff202020.toInt();c.drawText(n,x+5,20,p);x+=86};x=4f;groups[group]!!.forEach{t->p.color=if(t==tool)0xff8eafe0.toInt()else 0xffd3d0ca.toInt();c.drawRect(x,34f,x+62,86f,p);p.color=0xff202020.toInt();p.textSize=8f;c.drawText(label(t),x+4,62,p);x+=66}}
    private fun label(t:EditorTool)=when(t){EditorTool.WHOLE->"1/1";EditorTool.HALF->"1/2";EditorTool.QUARTER->"1/4";EditorTool.EIGHTH->"1/8";EditorTool.SIXTEENTH->"1/16";EditorTool.THIRTY_SECOND->"1/32";EditorTool.REST_WHOLE->"sil 1/1";EditorTool.REST_HALF->"sil 1/2";EditorTool.REST_QUARTER->"sil 1/4";EditorTool.REST_EIGHTH->"sil 1/8";EditorTool.REST_SIXTEENTH->"sil 1/16";EditorTool.REST_THIRTY_SECOND->"sil 1/32";EditorTool.DOT->".";EditorTool.DOUBLE_DOT->"..";EditorTool.SELECT->"select";EditorTool.ERASER->"gomme";EditorTool.TIE->"tie";EditorTool.SLUR->"slur";EditorTool.TUPLET->"3:2";else->t.name.lowercase()}
    private fun width(m:RationalMeasure)=max(210f,170f+m.events.size*42f+m.events.sumOf{1.0/max(.03125,it.duration.toDouble())}.toFloat()*1.5f)
    private fun score(c:Canvas){var y=35f;var x=20f;engine.measures.forEach{m->val w=width(m);measure(c,m,x,y,w);x+=w;y+=122f;x=20f}}
    private fun measure(c:Canvas,m:RationalMeasure,x:Float,y:Float,w:Float){p.color=0xff202020.toInt();p.style=Paint.Style.STROKE;p.strokeWidth=1.2f;repeat(5){c.drawLine(x,y+it*10,x+w,y+it*10,p)};c.drawLine(x,y,x,y+40,p);c.drawLine(x+w,y,x+w,y+40,p);p.style=Paint.Style.FILL;p.textSize=11f;c.drawText("${m.number}",x-16,y-7,p);p.textSize=30f;c.drawText("𝄞",x+7,y+31,p);p.textSize=14f;c.drawText("${m.beats}",x+42,y+12,p);c.drawText("${m.beatUnit}",x+42,y+30,p);val span=w-82;val start=x+68;m.events.sortedBy{it.onset}.forEach{e->drawEvent(c,e,start+e.onset.toDouble().toFloat()/m.capacity.toDouble()*span,y)}}
    private fun drawEvent(c:Canvas,e:RationalEvent,x:Float,y:Float){p.color=if(e.id==engine.selectedId)0xff315d9f.toInt()else 0xff181818.toInt();val ny=y+32-((e.pitch?:60)-64)/2f*5f;if(e.rest)rest(c,x,ny,e.duration)else note(c,e,x,ny);e.dynamic?.let{p.textSize=9f;c.drawText(it,x-5,y+61,p)};e.ornament?.let{p.textSize=8f;c.drawText(if(it.contains("STACCATO"))"•"else if(it.contains("FERMATA"))"𝄐"else "~",x-4,ny-14,p)};e.tuplet?.let{p.textSize=8f;c.drawText("${it.actual}:${it.normal}",x-4,ny-24,p)};if(e.tieStart)curve(c,x+4,ny+8,x+48,ny+8);if(e.slurStart)curve(c,x,ny-10,x+48,ny-10)}
    private fun note(c:Canvas,e:RationalEvent,x:Float,y:Float){p.style=if(e.duration<Fraction.HALF)Paint.Style.FILL else Paint.Style.STROKE;p.strokeWidth=1.5f;c.drawOval(x-6,y-4,x+6,y+4,p);if(e.duration<=Fraction.QUARTER)c.drawLine(x+5,y,x+5,y-28,p);if(e.duration<=Fraction.EIGHTH)c.drawLine(x+5,y-28,x+17,y-22,p);if(e.duration<=Fraction.SIXTEENTH)c.drawLine(x+5,y-22,x+17,y-16,p);if(e.duration<=Fraction.THIRTY_SECOND)c.drawLine(x+5,y-16,x+17,y-10,p);glyph(e.accidental).takeIf{it.isNotEmpty()}?.let{p.textSize=13f;c.drawText(it,x-17,y+5,p)};repeat(e.dots){c.drawCircle(x+11+it*5,y,1.7f,p)}}
    private fun rest(c:Canvas,x:Float,y:Float,d:Fraction){p.style=Paint.Style.FILL;when{d==Fraction.ONE->c.drawRect(x-7,y-5,x+7,y,p);d==Fraction.HALF->c.drawRect(x-7,y,x+7,y+5,p);d<=Fraction.EIGHTH->{val q=Path();q.moveTo(x,y-8);q.lineTo(x+7,y);q.lineTo(x-4,y+8);q.close();c.drawPath(q,p)}else->c.drawRect(x-2,y-6,x+2,y+6,p)}}
    private fun curve(c:Canvas,a:Float,b:Float,d:Float,e:Float){val q=Path();q.moveTo(a,b);q.quadTo((a+d)/2,b+10,d,e);c.drawPath(q,p)}
    private fun glyph(a:Accidental)=when(a){Accidental.SHARP->"♯";Accidental.FLAT->"♭";Accidental.NATURAL->"♮";Accidental.DOUBLE_SHARP->"𝄪";Accidental.DOUBLE_FLAT->"𝄫";else->""}
    override fun onTouchEvent(e:MotionEvent):Boolean{zoom.onTouchEvent(e);when(e.actionMasked){MotionEvent.ACTION_DOWN->{dx=e.x;dy=e.y;moving=false;return true};MotionEvent.ACTION_MOVE->{if(abs(e.x-dx)+abs(e.y-dy)>8)moving=true;if(moving&&e.y>90){scrollX=max(0f,scrollX+(dx-e.x)/scale);scrollY=max(0f,scrollY+(dy-e.y)/scale);dx=e.x;dy=e.y;invalidate()};return true};MotionEvent.ACTION_UP->{if(moving)return true;if(e.y<30){groups.keys.elementAtOrNull((e.x/86).toInt())?.let{group=it};invalidate();return true};if(e.y in 34f..90f){groups[group]?.getOrNull(((e.x-4)/66).toInt())?.let{tool=it};invalidate();return true};edit(e.x,e.y);return true}};return true}
    private fun edit(sx:Float,sy:Float){val x=sx/scale+scrollX;val yy=sy/scale-92+scrollY;var top=35f;engine.measures.forEachIndexed{i,m->val w=width(m);val left=20f;if(yy in top-12..top+55&&x in left..left+w){val span=w-82;val onset=Fraction.of(((x-(left+68)).coerceAtLeast(0f)/span*m.capacity.toDouble()*256).toLong(),256);val hit=m.events.minByOrNull{dist(it.onset,onset).toDouble()}?.takeIf{dist(it.onset,onset)<Fraction.of(1,16));apply(i,m,hit,onset,yy-top);return};top+=122}}
    private fun apply(i:Int,m:RationalMeasure,hit:RationalEvent?,onset:Fraction,y:Float){when(tool){EditorTool.SELECT->engine.select(i,hit?.id);EditorTool.ERASER->{engine.select(i,hit?.id);engine.removeSelected()};EditorTool.DOT->hit?.let{engine.updateDots(it.id,i,1)};EditorTool.DOUBLE_DOT->hit?.let{engine.updateDots(it.id,i,2)};EditorTool.TIE->hit?.let{engine.toggleTie(it.id,i)};EditorTool.SLUR->hit?.let{engine.toggleSlur(it.id,i)};EditorTool.TUPLET->hit?.let{engine.addTuplet(i,listOf(it.id))};EditorTool.TRILL,EditorTool.MORDENT,EditorTool.INVERTED_MORDENT,EditorTool.TURN,EditorTool.INVERTED_TURN,EditorTool.STACCATO,EditorTool.SHORT_STACCATO,EditorTool.ACCENT,EditorTool.FERMATA,EditorTool.TREMOLO,EditorTool.GRACE->hit?.let{engine.setOrnament(it.id,i,tool.name)};EditorTool.PPP,EditorTool.PP,EditorTool.P,EditorTool.MP,EditorTool.MF,EditorTool.F,EditorTool.FF,EditorTool.FFF->hit?.let{engine.setDynamic(it.id,i,tool.name.lowercase())};EditorTool.CRESCENDO,EditorTool.DIMINUENDO->hit?.let{engine.setDynamic(it.id,i,if(tool==EditorTool.CRESCENDO)"<" else ">")};else->{val d=when(tool){EditorTool.WHOLE,EditorTool.REST_WHOLE->MusicalDuration.WHOLE;EditorTool.HALF,EditorTool.REST_HALF->MusicalDuration.HALF;EditorTool.QUARTER,EditorTool.REST_QUARTER->MusicalDuration.QUARTER;EditorTool.EIGHTH,EditorTool.REST_EIGHTH->MusicalDuration.EIGHTH;EditorTool.SIXTEENTH,EditorTool.REST_SIXTEENTH->MusicalDuration.SIXTEENTH;EditorTool.THIRTY_SECOND,EditorTool.REST_THIRTY_SECOND->MusicalDuration.THIRTY_SECOND;else->null};d?.let{engine.add(i,hit?.onset?:engine.nextFreeOnset(i),it,pitch(y),4,tool.name.startsWith("REST"),Accidental.NONE)}}};invalidate()}
    private fun pitch(y:Float)=((64-(y-32)/5*2).toInt()).coerceIn(36,84);private fun dist(a:Fraction,b:Fraction)=if(a>b)a-b else b-a
    fun saveCurrent()=runCatching{store.save(engine,ScoreSession.fileName,ScoreSession.title,ScoreSession.composer,ScoreSession.tempo)}.isSuccess
}
