package org.notamusic.app.musicxml

import org.notamusic.app.domain.model.*
import org.notamusic.app.domain.music.MusicXmlExporter
import org.notamusic.app.domain.music.MusicXmlImporter
import java.io.InputStream
import java.io.OutputStream
import javax.xml.parsers.DocumentBuilderFactory
import javax.xml.transform.OutputKeys
import javax.xml.transform.TransformerFactory
import javax.xml.transform.dom.DOMSource
import javax.xml.transform.stream.StreamResult
import org.w3c.dom.Document
import org.w3c.dom.Element

class PlaceholderMusicXml : MusicXmlImporter, MusicXmlExporter {
 override fun export(score:Score,output:OutputStream){val d=DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();val r=d.createElement("score-partwise");r.setAttribute("version","3.1");d.appendChild(r);r.add("work",d).add("work-title",d,score.metadata.title);val id=r.add("identification",d);if(score.metadata.composer.isNotBlank())id.add("creator",d,score.metadata.composer).setAttribute("type","composer");val pl=r.add("part-list",d);score.parts.forEachIndexed{i,p->pl.add("score-part",d).also{x->x.setAttribute("id","P${i+1}");x.add("part-name",d,p.name)}};score.parts.forEachIndexed{pi,p->val pe=r.add("part",d);pe.setAttribute("id","P${pi+1}");val s=p.staves.firstOrNull()?:return@forEachIndexed;s.measures.forEach{m->val me=pe.add("measure",d);me.setAttribute("number",m.number.toString());val a=me.add("attributes",d);a.add("divisions",d,"16");a.add("key",d).add("fifths",d,score.keySignature.fifths.toString());a.add("time",d).also{t->t.add("beats",d,m.timeSignature.beats.toString());t.add("beat-type",d,m.timeSignature.beatType.toString())};a.add("clef",d).also{c->c.add("sign",d,if(s.clef==Clef.BASS)"F" else "G");c.add("line",d,if(s.clef==Clef.BASS)"4" else "2")};m.elements.sortedBy{it.onset}.forEach{e->writeNote(d,me,e)}}}}
 val t=TransformerFactory.newInstance().newTransformer();t.setOutputProperty(OutputKeys.INDENT,"yes");t.transform(DOMSource(d),StreamResult(output))}
 private fun writeNote(d:Document,me:Element,e:MusicElement){val n=me.add("note",d);if(e is Rest)n.add("rest",d) else if(e is Note){n.add("pitch",d).also{p->p.add("step",d,step(e.pitch));e.accidental.alter()?.let{x->p.add("alter",d,x.toString())};p.add("octave",d,e.octave.toString())}}else return;val q=when(e){is Note->e.duration;is Rest->e.duration;else->return};n.add("duration",d,when(q){Duration.WHOLE->"16";Duration.HALF->"8";Duration.QUARTER->"4";Duration.EIGHTH->"2";Duration.SIXTEENTH->"1";Duration.THIRTY_SECOND->"1"});n.add("voice",d,e.voice.toString());n.add("type",d,when(q){Duration.WHOLE->"whole";Duration.HALF->"half";Duration.QUARTER->"quarter";Duration.EIGHTH->"eighth";Duration.SIXTEENTH->"16th";Duration.THIRTY_SECOND->"32nd"});val dots=when(e){is Note->e.dots;is Rest->e.dots;else->0};repeat(dots.coerceIn(0,2)){n.add("dot",d)};if(e is Note)e.tie?.let{if(it.start)n.add("tie",d).setAttribute("type","start");if(it.end)n.add("tie",d).setAttribute("type","stop")}}
 override fun import(input:InputStream):Score{val d=DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(input);val title=(d.getElementsByTagName("work-title").item(0)?.textContent?:d.getElementsByTagName("movement-title").item(0)?.textContent?:"Untitled");val composer=d.getElementsByTagName("creator").item(0)?.textContent?:"";val fifths=d.getElementsByTagName("fifths").item(0)?.textContent?.toIntOrNull()?:0;val parts=mutableListOf<Part>();val pes=d.getElementsByTagName("part");for(i in 0 until pes.length){val pe=pes.item(i) as Element;val id=pe.getAttribute("id").ifBlank{"P${i+1}"};val name=partName(d,id,i);val ms=mutableListOf<Measure>();val mel=pe.getElementsByTagName("measure");for(j in 0 until mel.length){val me=mel.item(j) as Element;val ts=me.getElementsByTagName("time").item(0) as? Element;val beats=ts?.getElementsByTagName("beats")?.item(0)?.textContent?.toIntOrNull()?:4;val bt=ts?.getElementsByTagName("beat-type")?.item(0)?.textContent?.toIntOrNull()?:4;var on=0;val els=mutableListOf<MusicElement>();val ns=me.getElementsByTagName("note");for(k in 0 until ns.length){val n=ns.item(k) as Element;val type=n.getElementsByTagName("type").item(0)?.textContent?:continue;val du=when(type){"whole"->Duration.WHOLE;"half"->Duration.HALF;"quarter"->Duration.QUARTER;"eighth"->Duration.EIGHTH;"16th"->Duration.SIXTEENTH;"32nd"->Duration.THIRTY_SECOND;else->continue};val v=n.getElementsByTagName("voice").item(0)?.textContent?.toIntOrNull()?:1;val dots=n.getElementsByTagName("dot").length.coerceIn(0,2);val e=if(n.getElementsByTagName("rest").length>0)Rest(du,dots=dots,voice=v,onset=on)else{val p=n.getElementsByTagName("pitch").item(0) as? Element?:continue;val st=p.getElementsByTagName("step").item(0)?.textContent?:"C";val oct=p.getElementsByTagName("octave").item(0)?.textContent?.toIntOrNull()?:4;val al=p.getElementsByTagName("alter").item(0)?.textContent?.toIntOrNull();Note(basePitch(st),oct,du,when(al){-2->Accidental.DOUBLE_FLAT;-1->Accidental.FLAT;0->Accidental.NATURAL;1->Accidental.SHARP;2->Accidental.DOUBLE_SHARP;else->Accidental.NONE},dots=dots,voice=v,onset=on)};els+=e;on+=e.duration.quarterUnits};ms+=Measure(me.getAttribute("number").toIntOrNull()?:j+1,TimeSignature(beats,bt),elements=els,voiceCount=els.maxOfOrNull{it.voice}?:1)};val ins=Instrument(id,name);parts+=Part(id,name,listOf(Staff(instrument=ins,measures=ms))) };return Score(metadata=Metadata(title=title,composer=composer),keySignature=KeySignature(fifths),parts=parts)}
 private fun partName(d:Document,id:String,i:Int)=run{var n="Part ${i+1}";val s=d.getElementsByTagName("score-part");for(x in 0 until s.length){val e=s.item(x) as Element;if(e.getAttribute("id")==id){n=e.getElementsByTagName("part-name").item(0)?.textContent?:n;break}};n}
 private fun step(p:Int)=when((p%12+12)%12){0->"C";2->"D";4->"E";5->"F";7->"G";9->"A";else->"B"};private fun basePitch(s:String)=when(s){"C"->60;"D"->62;"E"->64;"F"->65;"G"->67;"A"->69;else->71};private fun Accidental.alter()=when(this){Accidental.DOUBLE_FLAT->-2;Accidental.FLAT->-1;Accidental.NATURAL->0;Accidental.SHARP->1;Accidental.DOUBLE_SHARP->2;Accidental.NONE->null}
 private fun Element.add(tag:String,d:Document,text:String?=null):Element{val x=d.createElement(tag);text?.let{x.textContent=it};appendChild(x);return x};private fun Document.add(tag:String,d:Document,text:String?=null)=createElement(tag).also{text?.let{it.textContent=text}}
}
