package org.notamusic.app.ui

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import org.notamusic.app.data.persistence.ScoreFileStore
import org.notamusic.app.domain.model.*
import org.notamusic.app.domain.music.ScoreFactory
import org.notamusic.app.ui.create.CreateScoreDraft
import org.notamusic.app.ui.create.InstrumentCatalog
import org.notamusic.app.ui.create.InstrumentOption
import org.notamusic.app.ui.editor.ScoreNotationView
import org.notamusic.app.ui.editor.ScoreSession
import java.io.File
import java.io.FileOutputStream

private fun Context.dp(n:Int)= (n*resources.displayMetrics.density).toInt()
private fun TextView.heading(){setTextColor(Color.rgb(31,33,37));typeface=Typeface.DEFAULT_BOLD}
private fun Button.action(){minHeight=context.dp(46);textSize=14f;isAllCaps=false}
private fun card(c:Context)=LinearLayout(c).apply{orientation=LinearLayout.VERTICAL;setPadding(c.dp(22),c.dp(18),c.dp(22),c.dp(18));setBackgroundColor(Color.WHITE)}
private fun Context.toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()

class ScoreCreationActivity:AppCompatActivity(){
    private var page=0;private lateinit var flip:ViewFlipper;private lateinit var next:Button;private lateinit var back:Button
    private lateinit var title:EditText;private lateinit var composer:EditText;private lateinit var bpm:EditText;private lateinit var marking:Spinner;private lateinit var meter:Spinner;private lateinit var key:Spinner;private lateinit var pickup:Spinner
    private val selected=linkedMapOf<String,InstrumentOption>()
    override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;build()}
    private fun build(){
        val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(244,241,235))}
        val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(24),dp(10),dp(24),dp(10));setBackgroundColor(Color.rgb(38,40,44))}
        h.addView(TextView(this).apply{text="New score";textSize=22f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD},LinearLayout.LayoutParams(0,dp(48),1f));h.addView(TextView(this).apply{text="1 INFO · 2 INSTRUMENTS · 3 MUSICAL SETUP";textSize=10f;setTextColor(Color.LTGRAY)});root.addView(h)
        flip=ViewFlipper(this).apply{setPadding(dp(26),dp(18),dp(26),dp(12))};flip.addView(info());flip.addView(instruments());flip.addView(setup());root.addView(flip,LinearLayout.LayoutParams(-1,0,1f))
        val nav=LinearLayout(this).apply{gravity=Gravity.END;setPadding(dp(18),dp(6),dp(18),dp(10));setBackgroundColor(Color.rgb(232,228,221))}
        back=Button(this).apply{text="Back";action();isEnabled=false;setOnClickListener{if(page>0){page--;flip.showPrevious();navUpdate()}}};next=Button(this).apply{text="Continue";action();setOnClickListener{if(page<2){if(page==0&&!valid())return@setOnClickListener;if(page==1&&selected.isEmpty()){toast("Select at least one instrument");return@setOnClickListener};page++;flip.showNext();navUpdate()}else create()}}
        nav.addView(back,LinearLayout.LayoutParams(dp(120),dp(48)));nav.addView(Space(this),LinearLayout.LayoutParams(dp(12),1));nav.addView(next,LinearLayout.LayoutParams(dp(150),dp(48)));root.addView(nav);setContentView(root)
    }
    private fun info():View{val b=card(this);b.addView(TextView(this).apply{text="Score information";textSize=24f;heading()});b.addView(TextView(this).apply{text="Define the composition identity and tempo.";textSize=14f;setTextColor(Color.DKGRAY);setPadding(0,dp(6),0,dp(14))});title=EditText(this).apply{hint="Composition title";setText("Untitled")};composer=EditText(this).apply{hint="Composer / author"};bpm=EditText(this).apply{hint="BPM";setText("120");inputType=InputType.TYPE_CLASS_NUMBER};marking=Spinner(this).apply{adapter=ArrayAdapter(this@ScoreCreationActivity,android.R.layout.simple_spinner_dropdown_item,listOf("Grave","Largo","Adagio","Andante","Moderato","Allegretto","Allegro","Vivace","Presto"));setSelection(6)};listOf(title,composer,bpm).forEach{b.addView(it,LinearLayout.LayoutParams(-1,dp(58)))};b.addView(marking,LinearLayout.LayoutParams(-1,dp(52)));return ScrollView(this).apply{addView(b)}}
    private fun instruments():View{val s=ScrollView(this);val b=card(this);b.addView(TextView(this).apply{text="Instrumentation";textSize=24f;heading()});val count=TextView(this).apply{textSize=13f;setTextColor(Color.DKGRAY);setPadding(0,dp(5),0,dp(12))};b.addView(count);InstrumentCatalog.grouped.forEach{(family,opts)->b.addView(TextView(this).apply{text=family.uppercase();textSize=11f;setTextColor(Color.rgb(111,87,46));typeface=Typeface.DEFAULT_BOLD;setPadding(0,dp(8),0,dp(4))});opts.forEach{o->b.addView(CheckBox(this).apply{text=o.instrument.name+if(o.grandStaff)" · grand staff" else "";textSize=15f;setOnCheckedChangeListener{_,on->if(on)selected[o.instrument.id]=o else selected.remove(o.instrument.id);count.text="${selected.size} part(s) selected"}},LinearLayout.LayoutParams(-1,dp(44)))}};count.text="0 part(s) selected";s.addView(b);return s}
    private fun setup():View{val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val l=card(this);val r=card(this);l.addView(TextView(this).apply{text="Musical setup";textSize=24f;heading()});meter=Spinner(this).apply{adapter=ArrayAdapter(this@ScoreCreationActivity,android.R.layout.simple_spinner_dropdown_item,listOf("4/4","2/2","2/4","3/4","3/8","6/8","1/4","5/4","7/8","9/8","11/8","12/8"))};key=Spinner(this).apply{adapter=ArrayAdapter(this@ScoreCreationActivity,android.R.layout.simple_spinner_dropdown_item,listOf("C major","G major","D major","A major","E major","B major","F major","Bb major","Eb major","Ab major","A minor","E minor","D minor"))};pickup=Spinner(this).apply{adapter=ArrayAdapter(this@ScoreCreationActivity,android.R.layout.simple_spinner_dropdown_item,listOf("No pickup","1 beat","2 beats","3 beats"))};label(l,"Time signature",meter);label(l,"Key signature",key);label(l,"Pickup",pickup);r.addView(TextView(this).apply{text="Ready to compose";textSize=24f;heading()});r.addView(TextView(this).apply{text="${selected.size} part(s)\n4/4 · C major\n120 BPM";textSize=15f;setTextColor(Color.DKGRAY);setPadding(0,dp(14),0,0)});row.addView(l,LinearLayout.LayoutParams(0,-1,1f));row.addView(Space(this),LinearLayout.LayoutParams(dp(14),1));row.addView(r,LinearLayout.LayoutParams(0,-1,1f));return row}
    private fun label(p:LinearLayout,s:String,v:View){p.addView(TextView(this).apply{text=s;textSize=12f;setTextColor(Color.DKGRAY);setPadding(0,dp(14),0,dp(5))});p.addView(v,LinearLayout.LayoutParams(-1,dp(52)))}
    private fun valid()=if(title.text.toString().isBlank()){title.error="Enter a title";false}else true
    private fun navUpdate(){back.isEnabled=page>0;next.text=if(page==2)"Create score" else "Continue"}
    private fun create(){val tm=meter.selectedItem.toString().split('/');val kn=key.selectedItem.toString();val fifth=mapOf("C" to 0,"G" to 1,"D" to 2,"A" to 3,"E" to 4,"B" to 5,"F" to -1,"Bb" to -2,"Eb" to -3,"Ab" to -4)[kn.substringBefore(' ') ]?:0;val draft=CreateScoreDraft(metadata=Metadata(title.text.toString().ifBlank{"Untitled"},composer=composer.text.toString()),instruments=selected.values.map{it.instrument},keySignature=KeySignature(fifth,kn.endsWith("minor")),timeSignature=TimeSignature(tm[0].toInt(),tm[1].toInt()),tempo=Tempo(bpm.text.toString().toIntOrNull()?.coerceIn(20,400)?:120,marking.selectedItem.toString()),pickupBeats=pickup.selectedItemPosition);ScoreSession.start(ScoreFactory().create(draft));startActivity(Intent(this,EditScoreActivity::class.java));finish()}
}

class OpenScoresActivity:AppCompatActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;refresh()};private fun refresh(){val store=ScoreFileStore(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(20),dp(26),dp(20));setBackgroundColor(Color.rgb(244,241,235))};root.addView(TextView(this).apply{text="Your scores";textSize=28f;heading()});store.list().forEach{name->val row=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setBackgroundColor(Color.WHITE)};row.addView(Button(this).apply{text=name;action();setOnClickListener{store.load(name)?.let{v->ScoreSession.engine=v.engine;ScoreSession.fileName=name;ScoreSession.title=v.title;ScoreSession.composer=v.composer;ScoreSession.tempo=v.tempo;startActivity(Intent(this@OpenScoresActivity,EditScoreActivity::class.java))}}},LinearLayout.LayoutParams(0,dp(58),1f));row.addView(Button(this).apply{text="Delete";action();setOnClickListener{if(store.delete(name))refresh()}},LinearLayout.LayoutParams(dp(100),dp(58)));root.addView(row,LinearLayout.LayoutParams(-1,dp(64)))};if(store.list().isEmpty())root.addView(TextView(this).apply{text="No saved scores yet.";textSize=16f;setTextColor(Color.DKGRAY)});setContentView(ScrollView(this).apply{addView(root)})}}

class SettingsActivity:AppCompatActivity(){private val p by lazy{getSharedPreferences("settings",MODE_PRIVATE)};override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(20),dp(26),dp(20));setBackgroundColor(Color.rgb(244,241,235))};root.addView(TextView(this).apply{text="Settings";textSize=28f;heading()});listOf("prompt" to "Prompt tone","scroll" to "Auto scroll","highlight" to "Highlight new elements","touch" to "Touch / dash line","numbers" to "Show measure numbers","tutorial" to "Tutorial").forEach{(k,l)->root.addView(CheckBox(this).apply{text=l;isChecked=p.getBoolean(k,k!="tutorial");setOnCheckedChangeListener{_,v->p.edit().putBoolean(k,v).apply()}})};root.addView(Button(this).apply{text="Restore defaults";action();setOnClickListener{p.edit().clear().apply();recreate()}});setContentView(ScrollView(this).apply{addView(root)})}}

class MetadataEditorActivity:AppCompatActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(20),dp(26),dp(20))};val t=EditText(this).apply{hint="Title";setText(ScoreSession.title)};val c=EditText(this).apply{hint="Composer";setText(ScoreSession.composer)};val v=EditText(this).apply{hint="BPM";setText(ScoreSession.tempo.toString());inputType=InputType.TYPE_CLASS_NUMBER};val m=EditText(this).apply{hint="Tempo indication";setText(ScoreSession.tempoMarking)};listOf(t,c,v,m).forEach{root.addView(it,LinearLayout.LayoutParams(-1,dp(58)))};root.addView(Button(this).apply{text="Save";action();setOnClickListener{ScoreSession.syncMetadata(t.text.toString(),c.text.toString(),v.text.toString().toIntOrNull()?:120,m.text.toString());finish()}});setContentView(root)}}

class EditScoreActivity:AppCompatActivity(){private lateinit var editor:ScoreNotationView;private val playback=org.notamusic.app.playback.PcmPlaybackController();override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;editor=ScoreNotationView(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val bar=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setBackgroundColor(Color.rgb(48,50,55))};bar.addView(TextView(this).apply{text=ScoreSession.title;setTextColor(Color.WHITE);textSize=16f;typeface=Typeface.DEFAULT_BOLD;setPadding(dp(8),0,dp(10),0)},LinearLayout.LayoutParams(0,dp(50),1f));fun b(s:String,a:()->Unit)=Button(this).apply{text=s;action();setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(70,73,79));setOnClickListener{a()}};bar.addView(b("Metadata"){startActivity(Intent(this,MetadataEditorActivity::class.java))});bar.addView(b("+ Measure"){ScoreSession.engine.addMeasure(ScoreSession.engine.measures.lastIndex);editor.invalidate()});bar.addView(b("Undo"){ScoreSession.engine.undo();editor.invalidate()});bar.addView(b("Redo"){ScoreSession.engine.redo();editor.invalidate()});bar.addView(b("Play"){playback.play(ScoreSession.engine,ScoreSession.tempo)});bar.addView(b("Stop"){playback.stop()});bar.addView(b("Save"){if(editor.saveCurrent())toast("Score saved")});bar.addView(b("Staffs"){startActivity(Intent(this,StaffConfigurationActivity::class.java))});bar.addView(b("Export"){startActivity(Intent(this,ShareScoreActivity::class.java))});root.addView(bar);root.addView(editor,LinearLayout.LayoutParams(-1,0,1f));setContentView(root)};override fun onDestroy(){playback.stop();super.onDestroy()}}

class StaffConfigurationActivity:AppCompatActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(20),dp(26),dp(20));setBackgroundColor(Color.rgb(244,241,235))};root.addView(TextView(this).apply{text="Staff configuration";textSize=28f;heading()});ScoreSession.score?.parts?.forEachIndexed{i,p->val c=card(this);c.addView(TextView(this).apply{text="${i+1}. ${p.name}";textSize=18f;heading()});p.staves.forEach{s->c.addView(TextView(this).apply{text="${s.displayName} · ${s.clef.name.lowercase()}";textSize=14f;setPadding(0,dp(8),0,0)})};root.addView(c)};setContentView(ScrollView(this).apply{addView(root)})}}

class ShareScoreActivity:AppCompatActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);requestedOrientation=android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(20),dp(26),dp(20))};root.addView(TextView(this).apply{text="Export score";textSize=28f;heading()});root.addView(Button(this).apply{text="MusicXML";action();setOnClickListener{exportXml()}});root.addView(Button(this).apply{text="MIDI";action();setOnClickListener{exportMidi()}});setContentView(root)};private fun exportXml(){try{val f=File(filesDir,ScoreSession.fileName+".musicxml");FileOutputStream(f).use{org.notamusic.app.musicxml.PlaceholderMusicXml().export(ScoreSession.currentScore(),it)};applicationContext.toast("MusicXML exported") }catch(e:Exception){applicationContext.toast("MusicXML export failed")}};private fun exportMidi(){try{val f=File(filesDir,ScoreSession.fileName+".mid");FileOutputStream(f).use{org.notamusic.app.midi.PlaceholderMidiRenderer().render(ScoreSession.currentScore(),it)};applicationContext.toast("MIDI exported")}catch(e:Exception){applicationContext.toast("MIDI export failed")}}}
