name: Build and Sign NotaMusic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore from Secret
        env:
          KEY_STORE_BASE64: ${{ secrets.SECRET_NOTAMUSIC }}
        run: |
          echo "$KEY_STORE_BASE64" | base64 -d > app/release.jks

      - name: Build Signed AAB & APK
        run: ./gradlew bundleRelease assembleRelease

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NotaMusic-Release-Builds
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
